# Generated by Django 3.2.5 on 2021-07-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=100)),
                ('pcode', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('Product_image', models.ImageField(blank=True, null=True, upload_to='upload/product')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
